### ISSUE TITLE
Account#showページをリロードするだけで検索回数がインクリメントされてしまう

### ISSUE THREAD

**Issue by kishida-bg** [kishida-bg/scam_scan#16]

**Comment by kishida-bg** [comment]
searchボタンに特異のパラメータを渡して判定する
`search_btn_pushed?`

**Comment by kishida-bg** [comment]
(@sohey-dr )
それだと何度もsearchボタンを押せばいいだけなので、
最終的には同じIPアドレスから不正に検索回数をインクリメントできないようにする

**Comment by sohey-dr** [comment]
そうすると、IPアドレスとかのアクセスログをどこかに残す感じですか？

**Comment by kishida-bg** [comment]
@sohey-dr 
それかlocalstrageなどに情報残しておけないかな〜と。IPアドレスのログ取るのやりすぎかな、、
同じブラウザからのインクリメントを一定期間できないようにするだけで十分か

**Comment by sohey-dr** [comment]
@kishida-bg 
後者がメリデメいい感じな気がする、、
それかこれとか
https://rails.densan-labs.net/form/double_submit_protection.html

**Comment by kishida-bg** [comment]
@sohey-dr 
https://github.com/kishida-bg/scam_scan/pull/23
これだけでいけた

**Comment by sohey-dr** [comment]
流石っす！
自分も今になって違う方法は思いつきましたが、とりあえずは全然こっちで良さそう。
